#!/usr/bin/env python
# Copyright (c) 2021 CVC.
#
# This work is licensed under the terms of the MIT license.
# For a copy, see <https://opensource.org/licenses/MIT>.

import rospy
from human_agent.human_agent import HumanAgent


def human_agent():
    rospy.init_node("dummy_agent")
    human_agent = HumanAgent()
    rospy.spin()


if __name__ == '__main__':
    try:
        human_agent()
    except rospy.ROSInterruptException:
        pass
