#!/usr/bin/env python
# Copyright (c) 2021 CVC.
#
# This work is licensed under the terms of the MIT license.
# For a copy, see <https://opensource.org/licenses/MIT>.

import rospy
from ros_map_agent.ros_map_agent import ROSMapAgent


def ros_map_agent():
    rospy.init_node("map_agent")
    ros_map_agent = ROSMapAgent()
    rospy.spin()


if __name__ == '__main__':
    try:
        ros_map_agent()
    except rospy.ROSInterruptException:
        pass
